---
spring:
  application:
    name: tpicap-interface
    lifecycle:
      timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:h2:file:./data/mngdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      spring:
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never
server:
  port: 11003

app:
  connection:
    ssl: false
    host: 204.179.96.165
#    host: 204.179.96.165
#    host: 204.179.96.168
    port: 6264
#    port: 6443
    proxyHost:
    proxyPort: -1
    key: devscrpstpic
    value: test
    online: true
  session:
    begin: "0 0 6 * * *"    # 6:00 AM daily in prod EDT time
    end: "0 0 20 * * *"     # 20:00 PM daily in prod EDT time
    refresh: 40000
    status: 240000
  pool:
    connector: 1
    processor: 4           # processor pool size
    recorder: 5            # recorder pool size
  tracing:
    path:
      success: tracing/messages/success       # success message folder
      failure: tracing/messages/failure       # failure message folder
      pending: tracing/messages/pending       # pending message folder
      raw: tracing/raw                        # Raw message folder
    archiving:
      age: 30
      interval: 86400000
      path: archive
    message:
      # ALL: business message and session message
      # BUSINESS: business message only
      serialize-level: BUSINESS
      # NONE: Nothing to trace (not recommended)
      # BUSINESS: businesss only
      # INBOUND: inbound message only
      # OUTBOUND: includes outbound
      content-level: INBOUND
      # to log message content
      detailed: true
      # 0: no housekeeping
      # n: days to clean
      housekeeping: 0
    scripting: true
  pooling:
    active: true
    path: tracing/pooling              # pooling forlder for testing
  ackOnBooking: false
  timezone: "America/New_York"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, shutdown
    health:
      show-details: always
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true